### ISSUE TITLE
Delete Pages

### ISSUE THREAD

**Issue by infoitservit** [pkerspe/yii2-simple-cms#7]
I can't find any way to delete a created page. Do it exists?!

**Comment by pkerspe** [comment]
Hi Denis,

Use the Context Menu when clicking on the page in the CMS page tree.

Von meinem iPhone gesendet

**Comment by infoitservit** [comment]
God, i think i'm stupid but...i can't find it! Could you send me a screenshot? Thanks!

**Comment by pkerspe** [comment]
Hi Denis, I am sorry, I mixed it up myself, the delete function is not yet pushed to the repo, it is still under developlment.
I will push a fix soon and let you know.
For now you can only set the visibility to hidden, then it will not show up in the frontend.

**Comment by pkerspe** [comment]
Denis, I created a new tag for version 0.3.
It now includes the delete function.
Since it also contains some other changes you need to run migration scripts to update the db fields (4 new fileds in db).
I also updated the ckeditor version in this release to the latest version.

Please let me know if it works for you.

**Comment by infoitservit** [comment]
It works! Thanks!
