### ISSUE TITLE
Hierarchy hidden from second level

### ISSUE THREAD

**Issue by infoitservit** [pkerspe/yii2-simple-cms#8]
If i create more than 2 levels of hierarchy, the navigation  menù in frontend does'n show these pages link

**Comment by pkerspe** [comment]
HI,

the CmsBootstrapNavbarWidget is a tow level navigation only, it is also stated in the php code doc in the file itself.
If you need more than two levels of navigation you should extend the navigation widget and implement your own type.

Have a look at schallschlucker\simplecms\widgets\CmsBootstrapNavbarWidget and implement your own run() function for a menu with more levels.
Currently the implementation is more of a proof of concept. It should be changed to read the complete Hierarchy tree in one db call rather than walking through the tree node by node and fetching the child node.
